name = "etchnft"

# Use the latest compatibility date for best feature support
compatibility_date = "2024-09-23"

# Enable Node.js polyfills for packages like Lucia
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "etchnft"
database_id = "269db405-82b3-4a9d-851f-e33510373867"

[ai]
binding = "AI"
